services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # ¡Mágico! Permite editar código sin reconstruir
    env_file:
      - ./backend/.env  # Lee tus claves automáticamente

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Accederás en localhost:3000
    depends_on:
      - backend
